/*
 * generated by Xtext
 */
package org.xtext.cg2009;

import org.eclipse.xtext.resource.IFragmentProvider;
import org.xtext.cg2009.resource.EntitiesFragmentProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntitiesRuntimeModule extends org.xtext.cg2009.AbstractEntitiesRuntimeModule {

	@Override
	public Class<? extends IFragmentProvider> bindIFragmentProvider() {
		return EntitiesFragmentProvider.class;
	}
}
