/*
* generated by Xtext
*/
package org.xtext.cg2009.contentassist;

import org.xtext.cg2009.contentassist.AbstractEntitiesProposalProvider;
/**
 * see http://wiki.eclipse.org/Xtext/Documentation#Content_Assist on how to customize content assistant
 */
public class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {

}
