/*
 * generated by Xtext
 */
package org.xtext.cg2009;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntitiesUiModule extends org.xtext.cg2009.AbstractEntitiesUiModule {

}
