/*
* generated by Xtext
*/
package org.xtext.example.contentassist;

import org.xtext.example.contentassist.AbstractEntitiesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {

}
