/*
 * generated by Xtext
 */
package org.xtext.example;

import org.eclipse.xtext.parser.antlr.IReferableElementsUnloader;
import org.eclipse.xtext.resource.IFragmentProvider;
import org.xtext.example.resource.EntitiesFragmentProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntitiesRuntimeModule extends org.xtext.example.AbstractEntitiesRuntimeModule {

	@Override
	public Class<? extends IFragmentProvider> bindIFragmentProvider() {
		return EntitiesFragmentProvider.class;
	}
	
	public Class<? extends IReferableElementsUnloader> bindIReferableElementsUnloader() {
		return IReferableElementsUnloader.GenericUnloader.class;
	}
}
