/*
* generated by Xtext
*/
package org.xtext.cg2009.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class EntitiesTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
